import { defineTable } from "convex/server";
import { v } from "convex/values";

export const authTables = {
  /**
   * Users table - stores user accounts for authentication
   * Migrated from: Prisma User + UserRole models
   */
  users: defineTable({
    firstName: v.string(),
    lastName: v.string(),
    middleName: v.optional(v.string()), // Middle name/patronymic
    username: v.string(),
    email: v.string(),
    passwordHash: v.string(), // bcrypt hash
    roles: v.array(
      v.union(
        v.literal("ADMIN"),
        v.literal("TEACHER"),
        v.literal("STUDENT"),
        v.literal("PARENT")
      )
    ),
    avatar: v.optional(v.string()), // Profile picture URL or storage ID
    theme: v.optional(v.union(v.literal("light"), v.literal("dark"), v.literal("lavanda"), v.literal("coral"), v.literal("graphite"))), // User theme preference
    locale: v.optional(v.union(v.literal("ru"), v.literal("kk"), v.literal("en"))),
    phone: v.optional(v.string()),
    office: v.optional(v.string()),
    department: v.optional(v.string()),
    degree: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index("by_username", ["username"])
    .index("by_email", ["email"]),

  /**
   * Permissions - defines resource + action access rules for roles
   * NEW: Dynamic RBAC implementation
   */
  permissions: defineTable({
    resource: v.string(),
    action: v.union(
      v.literal("navigate"),
      v.literal("read"),
      v.literal("write"),
    ),
    roles: v.array(
      v.union(
        v.literal("ADMIN"),
        v.literal("TEACHER"),
        v.literal("STUDENT"),
        v.literal("PARENT"),
      )
    ),
    description: v.optional(v.string()),
    activeFrom: v.optional(v.number()),
    activeTo: v.optional(v.number()),
  })
    .index("by_resource_action", ["resource", "action"])
    .index("by_action", ["action"]),

  /**
   * Permission history - audit trail for permission changes
   * NEW: Dynamic RBAC implementation
   */
  permissionHistory: defineTable({
    permissionId: v.id("permissions"),
    resource: v.string(),
    action: v.string(),
    changedBy: v.id("users"),
    changedAt: v.number(),
    previousRoles: v.array(
      v.union(
        v.literal("ADMIN"),
        v.literal("TEACHER"),
        v.literal("STUDENT"),
        v.literal("PARENT"),
      )
    ),
    newRoles: v.array(
      v.union(
        v.literal("ADMIN"),
        v.literal("TEACHER"),
        v.literal("STUDENT"),
        v.literal("PARENT"),
      )
    ),
    previousActiveFrom: v.optional(v.number()),
    previousActiveTo: v.optional(v.number()),
    newActiveFrom: v.optional(v.number()),
    newActiveTo: v.optional(v.number()),
    changeType: v.union(
      v.literal("created"),
      v.literal("updated"),
      v.literal("deleted"),
    ),
  })
    .index("by_permission", ["permissionId"])
    .index("by_changedBy", ["changedBy"])
    .index("by_changedAt", ["changedAt"]),

  /**
   * Exam sessions
   * Migrated from: sessionStore.ts
   */
  sessions: defineTable({
    shortName: v.string(),
    fullName: v.string(),
    academicYearId: v.id("academicYears"),
    semesterId: v.optional(v.id("academicYearSemesters")),
    startDate: v.string(),
    endDate: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index("by_academicYear", ["academicYearId"])
    .index("by_semester", ["semesterId"]),

  /**
   * Password change history - tracks when passwords are regenerated
   * NEW: For security auditing and tracking
   */
  passwordChangeHistory: defineTable({
    userId: v.id("users"), // User whose password was changed
    changedBy: v.optional(v.id("users")), // Admin who changed it (optional for self-service)
    changeType: v.union(
      v.literal("regenerated"), // Password regenerated by admin
      v.literal("reset"), // Password reset by user
      v.literal("initial") // Initial password creation
    ),
    teacherId: v.optional(v.string()), // Reference to teacher if applicable
    notes: v.optional(v.string()),
    createdAt: v.string(),
  })
    .index("by_userId", ["userId"])
    .index("by_teacherId", ["teacherId"])
    .index("by_createdAt", ["createdAt"])
    .index("by_userId_createdAt", ["userId", "createdAt"]),
};
