import { migrations } from "./index";

const migrateOne = (_ctx: any, doc: any) => {
  const updates: any = {};
  if (typeof doc.createdAt === "number") updates.createdAt = new Date(doc.createdAt).toISOString();
  if (typeof doc.updatedAt === "number") updates.updatedAt = new Date(doc.updatedAt).toISOString();
  if (typeof doc.publishAt === "number") updates.publishAt = new Date(doc.publishAt).toISOString();
  if (typeof doc.expiresAt === "number") updates.expiresAt = new Date(doc.expiresAt).toISOString();
  return Object.keys(updates).length > 0 ? updates : undefined;
};

export const m_academicYears = migrations.define({ table: "academicYears", migrateOne });
export const m_semesterDefinitions = migrations.define({ table: "semesterDefinitions", migrateOne });
export const m_academicYearSemesters = migrations.define({ table: "academicYearSemesters", migrateOne });
export const m_specialties = migrations.define({ table: "specialties", migrateOne });
export const m_courses = migrations.define({ table: "courses", migrateOne });
export const m_bases = migrations.define({ table: "bases", migrateOne });
export const m_positions = migrations.define({ table: "positions", migrateOne });
export const m_cabinets = migrations.define({ table: "cabinets", migrateOne });
export const m_disciplines = migrations.define({ table: "disciplines", migrateOne });
export const m_modules = migrations.define({ table: "modules", migrateOne });
export const m_users = migrations.define({ table: "users", migrateOne });
export const m_permissions = migrations.define({ table: "permissions", migrateOne });
export const m_permissionHistory = migrations.define({ table: "permissionHistory", migrateOne });
export const m_sessions = migrations.define({ table: "sessions", migrateOne });
export const m_passwordChangeHistory = migrations.define({ table: "passwordChangeHistory", migrateOne });
export const m_calendarEvents = migrations.define({ table: "calendarEvents", migrateOne });
export const m_ktps = migrations.define({ table: "ktps", migrateOne });
export const m_ktpDetails = migrations.define({ table: "ktpDetails", migrateOne });
export const m_journals = migrations.define({ table: "journals", migrateOne });
export const m_journalStudents = migrations.define({ table: "journalStudents", migrateOne });
export const m_marks = migrations.define({ table: "marks", migrateOne });
export const m_markHistory = migrations.define({ table: "markHistory", migrateOne });
export const m_journalClosureReminders = migrations.define({ table: "journalClosureReminders", migrateOne });
export const m_files = migrations.define({ table: "files", migrateOne });
export const m_offlineQueue = migrations.define({ table: "offlineQueue", migrateOne });
export const m_notifications = migrations.define({ table: "notifications", migrateOne });
export const m_announcements = migrations.define({ table: "announcements", migrateOne });
export const m_announcementCategories = migrations.define({ table: "announcementCategories", migrateOne });
export const m_students = migrations.define({ table: "students", migrateOne });
export const m_teachers = migrations.define({ table: "teachers", migrateOne });
export const m_teacherChangeHistory = migrations.define({ table: "teacherChangeHistory", migrateOne });
export const m_rupEntries = migrations.define({ table: "rupEntries", migrateOne });
export const m_distributionEntries = migrations.define({ table: "distributionEntries", migrateOne });
export const m_intermediateControls = migrations.define({ table: "intermediateControls", migrateOne });
export const m_finalControls = migrations.define({ table: "finalControls", migrateOne });
export const m_scheduledIntermediateControls = migrations.define({ table: "scheduledIntermediateControls", migrateOne });
export const m_scheduledFinalControls = migrations.define({ table: "scheduledFinalControls", migrateOne });
export const m_educationSchedules = migrations.define({ table: "educationSchedules", migrateOne });
export const m_vacations = migrations.define({ table: "vacations", migrateOne });
export const m_substitutions = migrations.define({ table: "substitutions", migrateOne });
export const m_makeupRequests = migrations.define({ table: "makeupRequests", migrateOne });
export const m_tests = migrations.define({ table: "tests", migrateOne });
export const m_testAssignments = migrations.define({ table: "testAssignments", migrateOne });
export const m_testResults = migrations.define({ table: "testResults", migrateOne });
export const m_workloads = migrations.define({ table: "workloads", migrateOne });
